name: rapid_pass_info
description: "Displays all your Rapid Passes in one place."
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  html: ^0.15.4
  http: ^1.2.1
  relative_time: ^5.0.0
  shared_preferences: ^2.2.3
  dynamic_color: ^1.7.0
  provider: ^6.1.2
  flutter_flip_card: ^0.0.6
  animated_reorderable_list: ^1.0.7
  flutter_localizations:
    sdk: flutter
  intl: any
  sqflite: ^2.4.0
  path: ^1.9.0
  reorderable_grid: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  sqflite_common_ffi: ^2.3.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/icon.png
