name: rapid_pass_info
description: "Displays all your Rapid Passes in one place."
publish_to: "none"

version: 2.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.6
  http: ^1.4.0
  relative_time: ^5.0.0
  dynamic_color: ^1.7.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  upgrader: ^12.5.0
  version: ^3.0.2
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  collection: ^1.19.1
  sliver_tools: ^0.2.12
  flutter_secure_storage: ^10.0.0
  provider: ^6.1.5
  grouped_list: ^6.0.0
  material_loading_indicator:
    git: git@github.com:ksokolovskyi/material_loading_indicator.git
  material_shapes:
    git: git@github.com:ksokolovskyi/material_shapes.git
  shared_preferences: any
  elegant_spring_animation: ^2.0.2
  google_fonts: ^8.0.2
  uuid: ^4.5.1
  nfc_manager: ^4.1.1
  nfc_manager_felica: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/icon.png
  fonts:
    - family: Lexend Deca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-VariableFont_wght.ttf
