name: rapid_pass_info
description: "Displays all your Rapid Passes in one place."
publish_to: "none"

version: 1.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.4
  http: ^1.2.1
  relative_time: ^5.0.0
  dynamic_color: ^1.7.0
  flutter_flip_card: ^0.0.6
  animated_reorderable_list: ^1.0.7
  flutter_localizations:
    sdk: flutter
  intl: any
  path: ^1.9.0
  reorderable_grid: ^1.0.10
  hive_ce: ^2.7.0+1
  hive_ce_flutter: ^2.1.0
  upgrader: ^11.3.0
  version: ^3.0.2
  package_info_plus: ^8.1.1
  url_launcher: ^6.3.1
  dropdown_search: ^6.0.1
  collection: ^1.18.0
  sliver_tools: ^0.2.12
  side_sheet: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.13
  hive_ce_generator: ^1.7.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/icon.png
  fonts:
    - family: Lexend Deca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-VariableFont_wght.ttf
