import 'package:rapid_pass_info/models/merged_transit_card.dart';

/// Dummy merged transit cards for testing and development.
final List<MergedTransitCard> dummyMergedCards = [
  MergedTransitCard(
    accountId: 'ACC001',
    cardNumber: '1234567890',
    name: 'Alice Rahman',
    hexCardNo: 'A1B2C3D4',
    cardType: 'Adult',
    serverStatus: 'Active',
    effectiveBalance: 1200.50,
    effectiveActivities: [
      CardActivity(
        timestamp: DateTime(2024, 6, 1, 9, 0, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.recharge,
        charge: 500.0,
        balanceAfter: 1200.50,
        phase: CardActivityPhase.recharge,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 5, 8, 30, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -30.0,
        balanceAfter: 1170.50,
        origin: 'Uttara',
        destination: 'Motijheel',
        phase: CardActivityPhase.trip,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 5, 9, 0, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -10.0,
        balanceAfter: 1160.50,
        origin: 'Uttara',
        destination: 'Motijheel',
        phase: CardActivityPhase.alighting,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 8, 7, 45, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -25.0,
        balanceAfter: 1135.50,
        origin: 'Dhanmondi',
        destination: 'Gulshan',
        phase: CardActivityPhase.trip,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 8, 8, 15, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -8.0,
        balanceAfter: 1127.50,
        origin: 'Dhanmondi',
        destination: 'Gulshan',
        phase: CardActivityPhase.alighting,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 12, 17, 20, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.issue,
        charge: -50.0,
        balanceAfter: 1077.50,
        phase: CardActivityPhase.issue,
      ),
    ],
    isLinked: true,
    isServerStale: false,
    nfcGapFillCount: 0,
    linkedIdm: 'IDM-001-2024',
  ),
  MergedTransitCard(
    accountId: 'ACC002',
    cardNumber: '9876543210',
    name: 'Babul Islam',
    hexCardNo: 'D4C3B2A1',
    cardType: 'Adult',
    serverStatus: 'Active',
    effectiveBalance: 800.00,
    effectiveActivities: [
      CardActivity(
        timestamp: DateTime(2024, 6, 2, 10, 0, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.recharge,
        charge: 300.0,
        balanceAfter: 800.00,
        phase: CardActivityPhase.recharge,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 6, 6, 30, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -45.0,
        balanceAfter: 755.00,
        origin: 'Mirpur',
        destination: 'Uttara',
        phase: CardActivityPhase.trip,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 6, 7, 0, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -12.0,
        balanceAfter: 743.00,
        origin: 'Mirpur',
        destination: 'Uttara',
        phase: CardActivityPhase.alighting,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 9, 11, 0, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -50.0,
        balanceAfter: 693.00,
        origin: 'Chittagong',
        destination: "Cox's Bazar",
        phase: CardActivityPhase.trip,
      ),
    ],
    isLinked: true,
    isServerStale: false,
    nfcGapFillCount: 0,
    linkedIdm: 'IDM-002-2024',
  ),
  MergedTransitCard(
    accountId: 'ACC003',
    cardNumber: '5555555555',
    name: 'Chanchal Chowdhury',
    hexCardNo: 'E5F6G7H8',
    cardType: 'Adult',
    serverStatus: 'Active',
    effectiveBalance: 1500.00,
    effectiveActivities: [
      CardActivity(
        timestamp: DateTime(2024, 6, 3, 8, 0, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.recharge,
        charge: 1000.0,
        balanceAfter: 1500.00,
        phase: CardActivityPhase.recharge,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 7, 14, 10, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -28.0,
        balanceAfter: 1472.00,
        origin: 'Savar',
        destination: 'Gulshan',
        phase: CardActivityPhase.trip,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 7, 14, 35, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -9.0,
        balanceAfter: 1463.00,
        origin: 'Savar',
        destination: 'Gulshan',
        phase: CardActivityPhase.alighting,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 11, 13, 0, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -80.0,
        balanceAfter: 1383.00,
        origin: 'Sylhet',
        destination: 'Dhaka',
        phase: CardActivityPhase.trip,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 15, 9, 30, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.recharge,
        charge: 250.0,
        balanceAfter: 1633.00,
        phase: CardActivityPhase.recharge,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 18, 18, 45, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.issue,
        charge: -100.0,
        balanceAfter: 1533.00,
        phase: CardActivityPhase.issue,
      ),
    ],
    isLinked: false,
    isServerStale: false,
    nfcGapFillCount: 0,
  ),
  MergedTransitCard(
    accountId: 'ACC004',
    cardNumber: '4444444444',
    name: 'Dipa Karmakar',
    hexCardNo: 'I9J0K1L2',
    cardType: 'Student',
    serverStatus: 'Active',
    effectiveBalance: 600.00,
    effectiveActivities: [
      CardActivity(
        timestamp: DateTime(2024, 6, 4, 9, 0, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.recharge,
        charge: 400.0,
        balanceAfter: 600.00,
        phase: CardActivityPhase.recharge,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 6, 16, 0, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -22.0,
        balanceAfter: 578.00,
        origin: 'Banani',
        destination: 'Dhanmondi',
        phase: CardActivityPhase.trip,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 6, 16, 30, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -6.0,
        balanceAfter: 572.00,
        origin: 'Banani',
        destination: 'Dhanmondi',
        phase: CardActivityPhase.alighting,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 10, 10, 0, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -30.0,
        balanceAfter: 542.00,
        origin: 'Khulna',
        destination: 'Barisal',
        phase: CardActivityPhase.trip,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 10, 10, 30, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -10.0,
        balanceAfter: 532.00,
        origin: 'Khulna',
        destination: 'Barisal',
        phase: CardActivityPhase.alighting,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 14, 8, 20, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.recharge,
        charge: 100.0,
        balanceAfter: 632.00,
        phase: CardActivityPhase.recharge,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 19, 12, 15, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.recharge,
        charge: 70.0,
        balanceAfter: 702.00,
        phase: CardActivityPhase.recharge,
      ),
    ],
    isLinked: true,
    isServerStale: false,
    nfcGapFillCount: 0,
    linkedIdm: 'IDM-004-2024',
  ),
  MergedTransitCard(
    accountId: 'ACC005',
    cardNumber: '3333333333',
    name: 'Ehsanul Haque',
    hexCardNo: 'M3N4O5P6',
    cardType: 'Adult',
    serverStatus: 'Active',
    effectiveBalance: 2000.00,
    effectiveActivities: [
      CardActivity(
        timestamp: DateTime(2024, 6, 5, 11, 0, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.recharge,
        charge: 2000.0,
        balanceAfter: 2000.00,
        phase: CardActivityPhase.recharge,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 9, 7, 0, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -35.0,
        balanceAfter: 1965.00,
        origin: 'Motijheel',
        destination: 'Uttara',
        phase: CardActivityPhase.trip,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 9, 7, 30, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -11.0,
        balanceAfter: 1954.00,
        origin: 'Motijheel',
        destination: 'Uttara',
        phase: CardActivityPhase.alighting,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 13, 10, 45, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -27.0,
        balanceAfter: 1927.00,
        origin: 'Gulshan',
        destination: 'Baridhara',
        phase: CardActivityPhase.trip,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 13, 11, 10, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.trip,
        charge: -7.0,
        balanceAfter: 1920.00,
        origin: 'Gulshan',
        destination: 'Baridhara',
        phase: CardActivityPhase.alighting,
      ),
      CardActivity(
        timestamp: DateTime(2024, 6, 17, 15, 30, 0),
        source: CardActivitySource.server,
        kind: CardActivityKind.recharge,
        charge: 150.0,
        balanceAfter: 2070.00,
        phase: CardActivityPhase.recharge,
      ),
    ],
    isLinked: false,
    isServerStale: false,
    nfcGapFillCount: 0,
  ),
];
